Misc enhancements

diff --git a/tasks/main.yml b/tasks/main.yml
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -1,50 +1,48 @@
 ---
 
-- name: Cron
-  block:
-    - name: "File {{ apt_upgrade_script }}"
-      ansible.builtin.copy:
-        dest: "/usr/local/bin/{{ apt_upgrade_script }}"
-        owner: root
-        group: root
-        mode: "0755"
-        content: |
-          #!/bin/bash
-          set -euf -o pipefail
+- name: "File {{ auto_upgrade_script }}"
+  ansible.builtin.copy:
+    dest: "{{ auto_upgrade_script }}"
+    owner: root
+    group: root
+    mode: "0755"
+    content: |
+      #!/bin/bash
+      set -euf -o pipefail
 
-          # shellcheck disable=SC2317
-          error_handler() {
-            local errno="$?"
-            echo "Error: ${BASH_SOURCE[1]}:${BASH_LINENO[0]}" \
-              "(${BASH_COMMAND} exited with status $errno)" >&2
-            exit "${errno}"
-          }
+      # shellcheck disable=SC2317
+      error_handler() {
+        local errno="$?"
+        echo "Error: ${BASH_SOURCE[1]}:${BASH_LINENO[0]}" \
+          "(${BASH_COMMAND} exited with status $errno)" >&2
+        exit "${errno}"
+      }
 
-          wait_for_successful_apt_update() {
-            # 720 minutes = 12 hours
-            local i
-            for (( i = 0; i < 720; i++ )); do
-              if apt-get update >/dev/null 2>&1; then
-                break
-              else
-                echo "No Internet connection. Wait 1 minute..."
-                sleep 60
-              fi
-            done
-          }
+      wait_for_successful_apt_update() {
+        # 720 minutes = 12 hours
+        local i
+        for (( i = 0; i < 720; i++ )); do
+          if apt-get update >/dev/null 2>&1; then
+            break
+          else
+            echo "No Internet connection. Wait 1 minute..."
+            sleep 60
+          fi
+        done
+      }
 
-          main() {
-            trap "error_handler" ERR
-            set -o errtrace
+      main() {
+        trap "error_handler" ERR
+        set -o errtrace
 
-            export DEBIAN_FRONTEND=noninteractive
+        export DEBIAN_FRONTEND=noninteractive
 
-            wait_for_successful_apt_update
+        wait_for_successful_apt_update
 
-            apt-get update
-            apt-get upgrade -y
-            apt-get autoremove --purge -y
-            apt-get clean -y
-          }
+        apt-get update
+        apt-get upgrade -y
+        apt-get autoremove --purge -y
+        apt-get clean -y
+      }
 
-          main "$@"
+      main "$@"
